#!/bin/sh
#
# preflight.sh - Pre-flighting a Ruby project before a version commit.
#
# Requirements:
# * git
# * Ruby Gems
# - cucumber
# - metrical
# - rspec
# - simple_cov
#
# simple_cov needs to be configured to generate the coverage/percentage.txt file,
# which will just have the numeric percentage result.

echo "Running test suites..."
rm coverage/resultset.yml
rake spec
rake cucumber

# the following requires simple_cov to be configured to generate the coverage/percentage.txt file.
if cat coverage/percentage.txt | grep -q "^100\.0*$" ; then
	# we have 100% coverage
	echo ""
else
	# we have < 100% coverage:
	echo "Incomplete code test coverage ($(cat coverage/percentage.txt)%)."
	open coverage/index.html
	exit 1
fi

# report on the code quality
echo "Generating Metrical reports..."
metrical
echo ""

# check the git status
echo "Checking version control status..."
gs="$(git status | tail -n 1)"
if echo $gs | grep -q "^nothing to commit" ; then
	# no uncommitted changes - so nothing to commit
	echo "Nothing to commit."
	exit 2
elif echo $gs | grep -q "^no changes added to commit" ; then
	# there are changes, but none have been staged for version control
	git status
	echo ""
	echo "Nothing has been staged for commit. Please use 'git add <path>' to stage files for commit."
	exit 3
else
 	# there are files to commit
	git status
	echo ""
	echo "Ready for commit ('git commit')."
	echo "Use 'git add <path>', first, if you want to add additional files for the commit."
fi
